apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kubernetes-app
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: felixle236/frontend
        ports:
          - containerPort: 4000