apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-logging
  namespace: kubernetes-logging
  labels:
    app: elasticsearch-logging
data:
  cluster.name: k8s-logs
  node.name: elasticsearch-logging
  network.host: "0.0.0.0"
  bootstrap.memory_lock: "false"
  discovery.zen.ping.unicast.hosts: elasticsearch-logging
  discovery.zen.minimum_master_nodes: "1"
  node.max_local_storage_nodes: "20"
  node.data: "true"
  node.master: "true"
  node.ingest: "false"
  xpack.security.enabled: "false"
  xpack.monitoring.enabled: "false"
  ES_JAVA_OPTS: "-Xms1g -Xmx1g"