apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-logging
  namespace: kubernetes-logging
  labels:
    app: elasticsearch-logging
data:
  elasticsearch.yml: |-
    # cluster.name: elasticsearch-logging
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    # cluster.initial_master_nodes: elasticsearch-logging
    # discovery.seed_hosts: elasticsearch-logging-cluster
    discovery.zen.minimum_master_nodes: 1
    node.max_local_storage_nodes: 20
    # node.name: elasticsearch-logging
    node.data: true
    node.master: true
    node.ingest: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
  ES_JAVA_OPTS: -Xms512m -Xmx512m