apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kubernetes-logging
  labels:
    app: elasticsearch-logging
spec:
  selector:
    app: elasticsearch-logging
  clusterIP: None
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: transport