apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kubernetes-logging
  labels:
    app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Elasticsearch"
spec:
  selector:
    app: elasticsearch-logging
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
