apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: kubernetes-logging
  labels:
    app: elasticsearch-logging
spec:
  selector:
    app: elasticsearch-logging
  ports:
  - name: http
    port: 9200
    targetPort: 9200

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging-cluster
  namespace: kubernetes-logging
  labels:
    app: elasticsearch-logging
spec:
  selector:
    app: elasticsearch-logging
  ports:
  - name: transport
    port: 9300
    targetPort: 9300