apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: kubernetes-app
  labels:
    app: chat-service
spec:
  selector:
    app: chat-service
  ports:
  - name: http
    port: 80
    targetPort: 5000