apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: kubernetes-app
  labels:
    app: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: pgadmin
      # initContainers:
      # - name: fix-permission
      #   image: busybox
      #   command: ['sh', '-c', 'sudo chown -R postgres /usr/local/var/postgres']