apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: kubernetes-app
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
  - port: 80
    name: pgadmin
    targetPort: 80