apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kubernetes-app
  labels:
    app: frontend
spec:
  selector:
   app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 4000