apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: kubernetes-app
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
  - port: 80
    name: minio
    targetPort: 9000
    protocol: TCP