apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
  namespace: kubernetes-app
  labels:
    app: minio
spec:
  storageClassName: minio
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: kubernetes-app
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  storageClassName: minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi