apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: chat
  namespace: kubernetes-app
  labels:
    app: gateway
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: chat.app.local
    http:
      paths:
      - backend:
          serviceName: chat-service
          servicePort: 80