apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: minio
  namespace: kubernetes-app
  labels:
    app: gateway
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: minio.local
    http:
      paths:
      - backend:
          serviceName: minio
          servicePort: 80