apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: kubernetes-app
  labels:
    app: authentication-service
spec:
  selector:
    matchLabels:
      app: authentication-service
  replicas: 2
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      initContainers:
        - name: run-migration
          image: felixle236/authentication-service
          command: ['sh', '-c', './node_modules/.bin/typeorm migration:run']
      containers:
      - name: authentication-service
        image: felixle236/authentication-service
        # resources:
        #   limits:
        #     cpu: 4
        #     memory: 4Gi
        #   requests:
        #     cpu: 1
        #     memory: 2Gi
        ports:
          - containerPort: 3001