apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: kubernetes-app
  labels:
    app: authentication-service
spec:
  selector:
    app: authentication-service
  ports:
  - name: http
    port: 80
    targetPort: 3001