apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: kubernetes-logging
  labels:
    app: logstash
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
