apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: kubernetes-app
  labels:
    app: postgres
data:
  POSTGRES_DB: node_core
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "123456"
  PGDATA: /var/lib/postgresql/data/pgdata