apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kubernetes-app
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.1
        imagePullPolicy: "IfNotPresent"
        # resources:
        #   limits:
        #     cpu: 4
        #     memory: 4Gi
        #   requests:
        #     cpu: 1
        #     memory: 2Gi
        ports:
          - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim