apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: kubernetes-app
  labels:
    app: postgres
spec:
  storageClassName: postgres
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: kubernetes-app
  labels:
    app: postgres
spec:
  storageClassName: postgres
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi